apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        # - image: luksa/kubia
        # we're going to use the container built locally
        - image: kubia
          name: kubia
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8080
